
services:

  postgres:
    image: postgres:15-alpine
    container_name: rdv-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rdv_pkfrc
      POSTGRES_USER: ritice
      POSTGRES_PASSWORD: ritice
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    volumes:
      - rdv_pgdata:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ritice -d rdv_pkfrc"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: rdv-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - rdv_pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres

  app:
    build: .
    container_name: rdv-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rdv_pkfrc
      SPRING_DATASOURCE_USERNAME: ritice
      SPRING_DATASOURCE_PASSWORD: ritice
    ports:
      - "8080:8080"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge


volumes:
  rdv_pgdata:
  rdv_pgadmin: